spring:
  application:
    name: gateway-service
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      gateway:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state:
          seconds: 30
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10
  retry:
    instances:
      gateway:
        max-attempts: 3
        wait-duration:
          seconds: 10


logging:
  level:
    feign: DEBUG

server:
  port: 8085